export const REQUEST_SEARCH_DATA = 'REQUEST_SEARCH_DATA';
export const RECEIVE_SEARCH_DATA = 'RECEIVE_SEARCH_DATA';
export const RECEIVE_SEARCH_DATA_FAILED = 'RECEIVE_SEARCH_DATA_FAILED';
export const REQUEST_SHOW_MORE = 'REQUEST_SHOW_MORE';
