export const REQUEST_SEARCH_DATA = 'REQUEST_SEARCH_DATA';
export const RECEIVE_SEARCH_DATA = 'RECEIVE_SEARCH_DATA';
export const RECEIVE_SEARCH_DATA_FAILED = 'RECEIVE_SEARCH_DATA_FAILED';
export const REQUEST_SHOW_MORE = 'REQUEST_SHOW_MORE';

export const GIF_MODAL_REQUEST_IMAGE = 'REQUEST_IMAGE';
export const GIF_MODAL_IMAGE_LOADED = 'IMAGE_LOADED';
export const GIF_MODAL_CANCEL_REQUEST_IMAGE = 'GIF_MODAL_CANCEL_REQUEST_IMAGE';

export const ADD_RECENT_SEARCH_LOCAL_STORAGE = 'ADD_RECENT_SEARCH_LOCAL_STORAGE';
